# Generated by Django 3.1.2 on 2020-10-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20201011_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='update_by',
            new_name='updated_by',
        ),
    ]
